version: "3"

services:
  reverse_proxy:
    image: caddy:2.0.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - SERVICE=app:${PORT}

  app:
    restart: always
    environment:
      - NODE_ENV=production

  mongodb:
    restart: always

volumes:
  caddy_data: